name: Portfolio Update

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  push:
    branches:
      - main
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Git Config
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git config user.name
          git config user.email
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      # - run: npm test // test script not availabe
      # - run: npm run build
      # - run: |
      #     if [ "${{ github.event_name }}" == "push" ] || \
      #        [ "${{ github.event_name }}" == "pull_request_target" ]; then
      #       npm run deploy
      #     fi
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: static_page
